services:
  client:
    build:
      context: ./client
      target: prod
    container_name: ww-client
    environment:
      - NODE_ENV=production
    image: ww-client:prod
    ports:
      - "8080:80"
